version: '3'

services:
  postgres:
    image: 'postgres'
    container_name: 'postgresdocker'
    ports:
    - 5432:5432
    environment:
      - 'POSTGRES_USER=postgres'
      - 'POSTGRES_HOST_AUTH_METHOD=trust'
      - 'POSTGRES_DB=postgres'